# 下载远程LLM代码评审组件，并直接对本项目，对于任何项目都可以按照词action文件去配置使用
name: Build and Run OpenAiCodeReview By Download remote code review sdk

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Make dir libs
        run: mkdir -p ./libs

      - name: Download code review sdk
        run: wget -O ./libs/openai-code-review-sdk-1.0.jar https://github.com/zck13771714479/zck-openai-code-review-logs/releases/download/v1.0/openai-code-review-sdk-1.0.jar
      - name: Get repository name
        id: repo-name
        run: echo "PROJECT=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Get branch name
        id: branch-name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get commit author
        id: commit-author
        run: echo "AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      - name: Get commit message
        id: commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Print repository, branch name, commit author, and commit message
        run: |
          echo "Repository name is ${{ env.PROJECT }}"
          echo "Branch name is ${{ env.BRANCH }}"
          echo "Commit author is ${{ env.AUTHOR }}"
          echo "Commit message is ${{ env.COMMIT_MESSAGE }}"  

      - name: Run Code Review
        run: java -jar ./libs/openai-code-review-sdk-1.0.jar
        env:
          # git配置
          LOG_REPOSITORY_URL: ${{vars.LOG_REPOSITORY_URL}}
          PROJECT: ${{env.PROJECT}}
          BRANCH: ${{env.BRANCH}}
          AUTHOR: ${{env.AUTHOR}}
          COMMIT_MESSAGE: ${{env.COMMIT_MESSAGE}}
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
          # llm配置
          API_URL: ${{vars.API_URL}}
          API_KEY: ${{secrets.API_KEY}}
          # 微信消息推送配置
          APPID: ${{secrets.APPID}}
          SECRET: ${{secrets.SECRET}}
          TOUSER: ${{secrets.TOUSER}}
          TEMPLATE_ID: ${{secrets.TEMPLATE_ID}}
