# sdk文件打jar包并且运行，供开发本组件时使用，生产部署时使用远程下载方式
name: Build and Run OpenAiCodeReview By Main Maven Jar

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy openai-code-review-sdk JAR
        run: mvn dependency:copy -Dartifact=com.openai.code.review:openai-code-review-sdk:1.0 -DoutputDirectory=./libs

      - name: Get repository name
        id: repo-name
        run: echo "PROJECT=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Get owner name
        id: owner-name
        run: echo "OWNER=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_ENV

      - name: Get commit SHA
        id: commit-sha
        run: echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Get branch name
        id: branch-name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get commit author
        id: commit-author
        run: echo "AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV

      - name: Get commit message
        id: commit-message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Print github api rul
        id: github-api-url
        run: echo "GitHub API URL is $GITHUB_API_URL"

      - name: Print repository, branch name, commit author, and commit message
        run: |
          echo "Repository name is ${{ env.PROJECT }}"
          echo "Branch name is ${{ env.BRANCH }}"
          echo "Commit author is ${{ env.AUTHOR }}"
          echo "Commit message is ${{ env.COMMIT_MESSAGE }}"  
          echo "Owner name is ${{env.OWNER}}"
          echo "Commit sha is ${{env.COMMIT_SHA}}"
          echo "GitHub API URL is $GITHUB_API_URL"

      - name: Run Code Review
        run: java -jar ./libs/openai-code-review-sdk-1.0.jar
        env:
          # git配置
          LOG_REPOSITORY_URL: ${{vars.LOG_REPOSITORY_URL}}
          PROJECT: ${{env.PROJECT}}
          BRANCH: ${{env.BRANCH}}
          AUTHOR: ${{env.AUTHOR}}
          COMMIT_MESSAGE: ${{env.COMMIT_MESSAGE}}
          GITHUB_TOKEN: ${{ secrets.CODE_TOKEN }}
          OWNER: ${{env.OWNER}}
          COMMIT_SHA: ${{env.COMMIT_SHA}}
          WRITE_TYPE: ${{vars.WRITE_TYPE}}
          # llm配置
          API_URL: ${{vars.API_URL}}
          API_KEY: ${{secrets.API_KEY}}
          # 微信消息推送配置
          APPID: ${{secrets.APPID}}
          SECRET: ${{secrets.SECRET}}
          TOUSER: ${{secrets.TOUSER}}
          TEMPLATE_ID: ${{secrets.TEMPLATE_ID}}
